---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-026dea5602e368e96"
  tasks:
    - name: Provision an EC2 instance.
      ec2:
        key_name: annieaws
        region: "us-east-2"
        groups: ['m5-ig-postgres-tag', 'default', 'm5-nginx-load-balanced-servers']
        instance_type: t2.micro
        image: "{{ ami_id }}"
        vpc_subnet_id: "{{ public_subnet1.subnet.id }}"
        instance_tags:
          Name: connect
          Module: 5
        wait: yes
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: connect
      register: dbEc2